ukm_husk_homepage:
    path: /
    defaults: { _controller: UKMHuskBundle:Default:input, kommune:0, fylke:0 }
    
ukm_husk_kommune:
    path:     /f-{fylke}/k-{kommune}/
    defaults: { _controller: UKMHuskBundle:Default:input, kommune:0 }
    methods: [GET]

ukm_husk_do:
    path: /f-{fylke}/k-{kommune}/
    defaults: { _controller: UKMHuskBundle:Default:save, kommune:0 }

ukm_husk_kommune_api:
    path: /api/f-{fylke}/k-{kommune}/
    defaults: { _controller: UKMHuskBundle:API:liste }